version: '3.2'

services:
  postgresql:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - './.docker/postgres:/bitnami/postgresql'
    environment:
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: ""

  rmq:
    image: "rabbitmq:3.8-management"
    hostname: "rmq"
    container_name: "rmq"
    environment:
            RABBITMQ_DEFAULT_USER: ""
            RABBITMQ_DEFAULT_PASS: ""
            RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes: 
      - ./.docker/rabbit:/var/lib/rabbitmq
    networks: 
      - app-network

  cache:
      image: "redis:6-alpine"
      hostname: "cache"
      container_name: app-cache
      ports: 
          - "6379:6379"
      networks:
          - app-network
networks: 
    app-network: {}
